name: Download and Save to Repo4
on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download File from Telegram
        run: |
          # دانلود فایل با استفاده از یوزر-اجنت مرورگر
          curl -L "https://t.me/rahgozar94725_ip/324" \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          -o "rahgozar_config.ehi"

      - name: Check if file is valid
        run: |
          # اگر فایل دانلود شده خیلی کوچک باشد یعنی فقط صفحه HTML دانلود شده
          FILE_SIZE=$(stat -c%s "rahgozar_config.ehi")
          if [ $FILE_SIZE -lt 5000 ]; then
            echo "Warning: File might be just an HTML page. Telegram blocked direct download."
          fi

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add latest config file"
          file_pattern: 'rahgozar_config.ehi'
