name: Telegram Downloader
on: [workflow_dispatch]

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # این خط اجازه اضافه کردن فایل به مخزن را می‌دهد
    steps:
      - uses: actions/checkout@v3

      - name: Download File from Telegram
        run: |
          # دانلود فایل با استفاده از لینک مستقیم پست 324
          curl -L "https://t.me/rahgozar94725_ip/324" -o dnstt_config.ehi

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dnstt_config.ehi
          git commit -m "Add latest config from Telegram" || echo "No changes to commit"
          git push
