name: Save Config to Repo2
on: [workflow_dispatch]

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download File from Telegram
        run: |
          # دانلود فایل با استفاده از لینک مستقیم نسخه وب
          # استفاده از کاربر مجازی برای جلوگیری از مسدود شدن
          curl -L "https://t.me/rahgozar94725_ip/324" \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36" \
          -o "rahgozar_config.ehi"

      - name: Commit and Push to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add rahgozar_config.ehi
          git commit -m "Add latest DNSTT config from Telegram" || echo "No changes to commit"
          git push
