name: Telegram Direct Downloader
on: [workflow_dispatch]

jobs:
  download_file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Download .ehi File
        run: |
          # دانلود فایل از پست 324 کانال
          yt-dlp --get-filename -o "my_config.ehi" "https://t.me/rahgozar94725_ip/324"
          yt-dlp "https://t.me/rahgozar94725_ip/324" -o "my_config.ehi"

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add my_config.ehi
          git commit -m "Fetched real .ehi file" || echo "No changes"
          git push
